[workspace]
members = ["parser"]

[package]
name = "f_prime"
version = "0.1.0"
edition = "2021"
authors = ["Emmett Rayes <emmett.rayes@icloud.com>"]
repository = "https://github.com/emmett-rayes/f-prime"

[dependencies]
f_prime_parser = {path = "parser"}
